language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

jobs:
  incude:
    - stage: "Tests"
      name: "API Tests"
      scripts: behave --tags="@api_test"
      name : "UI Test"
      scripts: behave --tags="@ui_test"